FairwindsOps/insights-docs

- features/cluster-comparison.md
- installation/getting-started.md
- management/delete.md
- management/membership.md
- plugins/new.md
- plugins/rbac-reporter.md
- plugins/release-watcher.md
- plugins/trivy.md
- plugins/workloads.md
- release-notes.md
> Fix some copy

- release-notes.md
> 1.3.0 release notes

- plugins/new.md
Not quite ready to go - need to change some database logic on the backend before this is working 100%
> start adding custom report languaage

- README.md
- installation/getting-started.md
Fixed a couple links and fixed the capitalization on kube-bench.
> Updates for release 1.7

- reports/opa.md
Fixes a master -> main typo in insights-plugins link
> Fix path to insights-plugins repo

- docs/reports/opa.md
Adds to OPA docs for run environments, this probably needs better wording.
> Add start of docs for run environments

- docs/reports/opa.md
Adds to the docs for OPA how to specify clusters
> Add docs for OPA clusters

- docs/reports/opa.md
I missed the closing tag on the yaml block!
> Add missing closign tag

- docs/reports/opa.md
Based on [Add Rules engine to CLI](https://github.com/FairwindsOps/insights-cli/pull/10)
> Update directory structure for OPA checks

- docs/reports/opa.md
Oops - I think we were not ready to merge that.
> Revert "Update directory structure for OPA checks"

- docs/reports/opa.md
> Revert "Revert "Update directory structure for OPA checks""

- docs/.vuepress/config-extras.js
- docs/.vuepress/styles/index.styl
- docs/README.md
- docs/self-hosted/database.md
- docs/self-hosted/email.md
- docs/self-hosted/file-storage.md
- docs/self-hosted/ingress.md
- docs/self-hosted/installation.md
- docs/self-hosted/sessions.md
This combines a bit of Bader's work, our existing docs in the Insights repo, and some new changes
> Self-hosted docs

- docs/release-notes.md
> 4.0-release-notes

- docs/self-hosted/installation.md
Fixes the secret values and removes the explicit setting tag.
> Fix self hosted docs

- docs/.vuepress/enhanceApp.js
It works! I just forgot a path.
> add redirect path

- docs/release-notes.md
Fixes links for the new structure
> Fix release note links

- docs/release-notes.md
> fixing typos and formatting issues

- docs/release-notes.md
> add 4.4.0 release notes

- docs/.vuepress/config-extras.js
- docs/technical-details/self-hosted/integrations.md
> add self-hosted integrations

- docs/release-notes.md
Added a few more specific around the 6.5.0 release
> A few more specifics around the 6.5.0 release

- docs/release-notes.md
> Update release notes for 7.1.0

- docs/release-notes.md
Updating release notes for 7.2.0
> Update release notes for 7.2.0

- docs/release-notes.md
Update release notes for 7.3.0
> Update release docs for 7.3.0

- docs/release-notes.md
* [ X] I have updated/added any relevant documentation
Updating release notes for 7.4.0
> Update release notes for 7.4.0

- docs/release-notes.md
> Update release notes for 7.6.0

- README.md
- docs/.vuepress/config.js
- docs/.vuepress/theme/layouts/Layout.vue
- docs/package-lock.json
> Update documentation from template

- docs/release-notes.md
Update release notes for 7.7.0
> Update release notes for 7.7.0

- docs/release-notes.md
Update release notes for 7.8.0
> Update release notes for 7.8.0

- docs/release-notes.md
Update release notes for 7.9.0
> Update release notes for 7.9.0

- docs/technical-details/self-hosted/installation.md
* [ X] I have updated/added any relevant documentation
Remove alpha indication from self hosted
> Remove alpha indication from self hosted

- docs/release-notes.md
* [ X] I have signed the CLA
Update release notes for 7.10.0
> Update release notes for 7.10.0

- docs/installation/admission/setup.md
- docs/installation/ci/setup.md
- docs/technical-details/self-hosted/sessions.md
This PR fixes # Documentation changes
* [ X I have updated/added any relevant documentation
This PR intends to make slight tweaks to the documentation.
> Making small tweaks to AC, CI, and self-hosted install

- docs/release-notes.md
Update release notes for 7.11.0
> Update release notes for 7.11.0

- docs/technical-details/architecture/architecture.md
Update egress docs
Updated egress docs
> update egress docs

- docs/release-notes.md
Update release notes for 7.12.0
> Update release notes for 7.12.0

- docs/technical-details/reports/aws-costs.md
Add IAM example for accessing CUR data
Add IAM example for accessing CUR data
> add iam role to aws costs docs

- docs/release-notes.md
> Update release notes for 7.14.0

- docs/release-notes.md
Update release notes for 8.0.0
Update release notes for 8.0.0
> Update release notes for 8.0.0

- docs/release-notes.md
Update release notes for 8.1.0
> Update release notes for 8.1.0

- docs/release-notes.md
Update release notes for 8.2.0
> Update release notes for 8.2.0

- docs/release-notes.md
Update release notes for 8.4.0
> Update release notes for 8.4.0

- docs/.vuepress/config-extras.js
- docs/installation/ci/autoscan.md
- docs/release-notes.md
Update release notes and documentation for 8.5.0
> Update release notes and documentation for 8.5.0

- docs/installation/ci/github.md
updating Connect to GitHub docs to support AutoScan
Update docs to support AutoScan work
Text changes
> updating Connect to GitHub docs

- docs/installation/ci/setup.md
updating CI setup docs to support new UI flow
updating CI setup docs to support new UI flow
> updating CI setup docs to support new UI flow

- docs/installation/ci/about.md
Help customers understand their shift-left options
Add better docs around CI/CD vs Autoscan
> added table comparing Auto-Scan

- docs/release-notes.md
Update release notes for 8.6.0
> Update release notes for 8.6.0

- docs/first-steps/cost-efficiency.md
Clarify the average total cost
Doc edits
> Clarifying Avg Total Cost calculation

- docs/release-notes.md
Update release notes for 8.7.0
> Update release notes for 8.7.0

- docs/configure/ci/configuration.md
This accompanies [these changes to the CI plugin Helm values behavior](https://github.com/FairwindsOps/insights-plugins/pull/652) and should not be merged until the above PR has been merged.
Update CI docs with new Helm values options and priorities
[Internal Ticket FWI-1911](https://fairwinds.myjetbrains.com/youtrack/issue/FWI-1911)
> FWI-1911 - Update CI docs to reflect new Helm values behavior

- docs/code/sample-reports.md
- docs/technical-details/architecture/architecture.md
- docs/technical-details/reports/supported-checks.md
> Removing kubesec

- docs/.vuepress/config-extras.js
The previously added CLI policies configuration documentation had not be added to the docs side-bar - this fixes that.
> Add CLI policies configuration docs to the side-bar

- docs/release-notes.md
Update release notes for 8.8.0
> Update release notes for 8.8.0

- docs/first-steps/cost-efficiency.md
Added some information about how goldilocks and prometheus compare
> Goldilocks vs prometheus edits

- docs/technical-details/reports/resource-metrics.md
> Improving prometheus docs

- docs/release-notes.md
> Update release notes

- docs/configure/cli/automation-rules.md
- docs/configure/cli/cli.md
- docs/configure/cli/opa.md
- docs/installation/admission/setup.md
- docs/installation/agent/setup.md
- docs/installation/agent/troubleshooting.md
- docs/installation/ci/autoscan.md
- docs/installation/ci/github.md
- docs/installation/ci/insights-ci-script.md
Update CLI docs for OPA Policies
> Update CLI docs for OPA Policies

- docs/installation/sso/sso.md
> Update SSO installation docs

- docs/configure/cli/settings.md
- docs/configure/policy/policy.md
- docs/release-notes.md
Update release notes for 8.10.0
> Update release notes for 8.10.0

- .circleci/config.yml
Insights.docs.fairwinds.com doesn't match <reponame>.docs.fairwinds.com
Add a newly created parameter
Also, I tested it this time
> Add bucket name override

- docs/configure/cli/opa.md
Update the CLI documentation to describe options for specifying whether  an OPA Policy is expected to output an Action Item.
> Update the CLI OPA docs to include specifying success/failure when validating policies

- docs/release-notes.md
Update release notes for 9.1.0
> Update release notes for 9.1.0

- docs/release-notes.md
Update release notes for 9.2.0
> Update release notes for 9.2.0

- docs/release-notes.md
Update release docs for 9.3.0 release
> Update release docs for 9.3.0 release

- docs/installation/ci/about.md
being more explicit about public vs private image scanning
be more explicit about Auto-Scan's limitation around private images
> updates to CI about docs

- docs/.vuepress/config-extras.js
- docs/configure/automation/integrations.md
- docs/installation/integrations/azure.md
- docs/installation/integrations/jira.md
> Add Azure integration docs

- docs/installation/ci/about.md
- docs/release-notes.md
Update release notes for 9.4.0
> Update release notes for 9.4.0

- docs/release-notes.md
Update release notes for 9.6.0
> Update release notes for 9.6.0

- docs/configure/automation/integrations.md
- docs/installation/integrations/azure.md
- docs/release-notes.md
Update documentation for release 9.7.0
> Update documentation for release 9.7.0

- docs/release-notes.md
Update release notes for 9.8.0
> Update release notes for 9.8.0

- docs/configure/automation/integrations.md
> Added secrects doc

- docs/release-notes.md
Update release notes for 9.9.0
> Update release notes for 9.9.0

- docs/.vuepress/config-extras.js
- docs/README.md
- docs/technical-details/architecture/architecture.md
- docs/technical-details/security/security.md
> add SLO docs

- docs/configure/automation/integrations.md
> Fix secret docs

- docs/configure/automation/rules.md
- docs/release-notes.md
Update release notes for 9.11.0
> Update release notes for 9.11.0

- docs/release-notes.md
Update release notes for 9.12.0
> Update release notes for 9.12.0

- docs/release-notes.md
Update release notes for 9.13.0
> Update release notes for 9.13.0

- docs/configure/automation/integrations.md
- docs/installation/integrations/azure.md
- docs/installation/integrations/jira.md
- docs/release-notes.md
> Add some notes on third party ticket closing

- docs/release-notes.md
> Update release notes for 10.0

- docs/configure/ci/autoscan.md
> added troubleshooting info for helm

- docs/configure/ci/autoscan.md
- docs/configure/ci/configuration.md
> added flux example

- docs/configure/ci/configuration.md
- docs/installation/ci/insights-ci-script.md
This PR fixes some spacing issues in the fairwinds-insights.yaml
> Fix spacing in fairwinds-insights.yaml

- docs/configure/cli/automation-rules.md
> Fix typo in automation-rules.md

- docs/release-notes.md
> Add terraform update to release notes

- docs/.vuepress/config-extras.js
- docs/first-steps/policy-enforcement.md
How to use Fairwinds Insights' Policy features. This will live under the "Common Use Cases" nav.
> Create policy-enforcement docs

- docs/first-steps/policy-enforcement.md
This PR fixes some typos in the policy enforcement docs.
> More typos fixed in Policy Enforcement docs

- docs/configure/cli/automation-rules.md
> FWI-3435: Docs for validate rules

- docs/configure/cli/automation-rules.md
> Updated Colons to periods

- docs/technical-details/reports/falco.md
> Remove Beta text from Falco report page

- docs/configure/automation/rules.md
> Added is.Changed + context to Automation Rule Docs (LC)

- docs/first-steps/cost-efficiency.md
> Remove cost strategy docs

- docs/release-notes.md
> Update release notes for 12.4.0

- .github/workflows/static.yml
- docs/.vuepress/config-extras.js
an attempt to create a staging env to share my proposed changes
github action to deploy a staging env
s3 maybe?
> Create staging deploy via gh pages

- docs/release-notes.md
since we only released BE, this will be confusing for users, so i removed
> removed "automated compliance evidence" line

- docs/configure/automation/integrations.md
> Custom fields docs

- docs/configure/automation/integrations.md
> New create tickets fields

- docs/configure/automation/integrations.md
> Added issue type examples

- README.md
This PR takes some feedback from the marketing team
> Update README.md per marketing

- docs/features/automation-rules.md
> Fix secrets docs

- docs/features/automation-rules.md
> Update automation-rules.md - hyperlinked ticketing docs

- docs/release-notes.md
Notifying customers about Insights Agent 22.0.0 introducing new policies that may cause Admission Controller blocking scenarios.
> added note about Polaris policies

- docs/features/automation-rules.md
> Improving customizable fields docs

- docs/features/automation-rules.md
> Improved customizable fields docs

- docs/features/admission-controller.md
removed line that just linked to the next paragraph
> Update admission-controller.md remove extra line

- docs/features/automation-rules.md
> Improved customizable fields doc

- docs/features/automation-rules.md
> adding podLabels spec

- docs/.vuepress/config-extras.js
- docs/README.md
- docs/technical-details/reports/kyverno.md
- add kyverno information to docs
- added page for kyverno
- added link for the kyverno report to show up in the left nav
> feature: added information for kyverno report

- docs/technical-details/reports/aws-costs.md
> Fix hard-coded bucket name for aws costs

- docs/technical-details/reports/kyverno.md
> Add more info to kyverno docs

- docs/.vuepress/config-extras.js
- docs/technical-details/agent/agent-installation-rbac.md
Add an RBAC role that can be used to install the insights-agent and insights-admission charts.
> Add an rbac role that can be used for installing the charts

- docs/features/infrastructure-as-code-scanning.md
Add clarification on the exemptions for filename.
Added a sentence.
> indicate that filename exemptions support wildcards

- docs/features/policies.md
> Remove use of concat in OPA

- docs/features/policies.md
This PR fixes our OPA loops. Rego, amirite?
> fix OPA loops

- docs/features/automation-rules.md
> Added Jira Basic Auth config

- docs/features/automation-rules.md
> Added Jira customizable description example

- docs/.vuepress/config-extras.js
- docs/technical-details/agent/collecting-diagnostics.md
> FWI-1478 Add docs for collecting diagnostic info using insights_collect script

- docs/technical-details/agent/agent-installation-rbac.md
Publishes the Insights Agent  Kubernetes support window to the Insights docs sites.
> Added K8s support n-3

- docs/technical-details/reports/kyverno.md
> Add some kyverno docs about how policyreport/clusterpolicyreport metadata maps to action items

- docs/.vuepress/config-extras.js
- docs/technical-details/reports/cloud-costs.md
- docs/technical-details/reports/resource-metrics.md
> Added Cloud Costs plug-in documentation

- docs/release-notes.md
Formatting updates to release notes. Highlighting new features.
> Formatting updates to release notes

- docs/technical-details/reports/aws-costs.md
- docs/technical-details/reports/cloud-costs.md
> Added tagprefix doc for AWS and Cloud Costs

- docs/technical-details/reports/cloud-costs.md
- docs/technical-details/reports/falco.md
Some formatting edits to cloudcosts and falco pages
> formatting changes to cloudcosts and falco

- docs/release-notes.md
- typos and spelling errors
- removes reference to new GitHub comments - this was shipped in a previous release
- provides update on new Repo Scanning feature
> doc updates to include repo scanning feature

- docs/features/in-cluster-scanning.md
- docs/first-steps/cost-efficiency.md
Added some docs for AI  deletion and efficiency score calculation
> docs for AI deletion and efficiency score

- docs/release-notes.md
Adding a link to the Changlog for the Insights Agent
> Adding a link to the Changlog for the Insights Agent

- docs/features/app-groups.md
- docs/features/policy-mappings.md
updates to appgroups and policy mapping docs
> updates to appgroups and policy mapping docs

- docs/technical-details/reports/resource-metrics.md
Information on configuring prometheus-metrics with Azure Monitor managed service for Prometheus
> resource-metrics azure monitor configuration

- docs/technical-details/reports/right-sizer.md
Add documentation for the rebrand of `right-sizer` to Automated Right-sizing + OOMKill detection, outline breaking changes in the Insights Agent version `4.0`
> [FWI-5698] Add documentation for right-sizer rebrand

- docs/technical-details/reports/right-sizer.md
> [FWI-5698] Apply some fixes for right-sizer docs

- docs/technical-details/reports/right-sizer.md
Added some details about the BETA program
> Added note around beta program

- docs/technical-details/reports/right-sizer.md
added more details on BETA program
> added more details on BETA program

- docs/features/admission-controller.md
- docs/features/policy-mappings.md
- docs/first-steps/policy-enforcement.md
- docs/technical-details/reports/cloud-costs.md
This updates our Policy Enforcement docs to consider App Groups and Policy Mappings going forward.
> Updates to Policy Enforcement docs

- docs/technical-details/reports/resource-metrics.md
GCP changed links to their docs, this adjusts our docs to reflect the changes.
> fixing gcp links

- docs/features/insights-cli.md
Improves the CLI documentation.
> Update insights-cli.md with CLI usage examples and logs events

- docs/technical-details/reports/cloud-costs.md
- docs/technical-details/reports/resource-metrics.md
> Updating Managed Prometheus docs

- docs/features/insights-cli.md
- Update documentation on how to name directory and files when wanting to use OPA v2.
> add documentation on filename and structure to use opa v2

- docs/technical-details/reports/cloud-costs.md
Fix the provider terraform for GCP integration
> [INSIGHTS-137] fix google terraform provider code

- docs/technical-details/reports/right-sizer.md
> Updated vpa right sizer doc

- docs/technical-details/reports/right-sizer.md
> Added enableClosedBeta

- docs/release-notes.md
> chore: Update release notes for bug fixes and enhancements

- docs/technical-details/reports/right-sizer.md
> Added right-sizer example to specific container name

- docs/features/team-management.md
> INSIGHTS-228 Update SSO docs with new fields support

- docs/features/insights-cli.md
- docs/features/policies.md
- Add custom policies with opa
> [INSIGHTS-224] - Add custom OPA library docs

- docs/features/automation-rules.md
> INSIGHTS-242 - documentation for automation rules app groups membership functions

- docs/technical-details/reports/resource-metrics.md
> Fixing docs

- docs/technical-details/reports/resource-metrics.md
> Updated docs for GKE Autopilot

- docs/features/insights-cli.md
> fix docs for automation rules

- docs/features/policies.md
This PR fixes internal INSIGHTS-339
- add external sources opa support documentation
> INSIGHTS-339 - add external sources opa support documentation

- docs/technical-details/reports/resource-metrics.md
- docs/technical-details/reports/workloads.md
> Workload and Prometheus schedule

- docs/release-notes.md
> add date to releases

- docs/technical-details/reports/right-sizer.md
> INSIGHTS-449 Fix VPA docs

- docs/features/app-groups.md
> INSIGHTS-511 Documentation spelling error

- docs/features/insights-cli.md
> Added libs for opa

- docs/features/insights-cli.md
> INSIGHTS-536 Add OPA v1 deprecation to insights docs

- docs/features/integrations.md
> add Microsoft Teams integration documentation

- docs/features/insights-cli.md
- Refactor previous documentation
- Add multiple success/failure test files support
> INSIGHTS-589 - enhance documentation for batch validation & multiple test files of OPA policies

- docs/release-notes.md
> Update release notes for versions 16.3.44 and 16.3.43

- docs/.vuepress/config-extras.js
- docs/features/ticketing.md
> INSIGHTS-715 - Add ticketing feature documentation and update config for integration

- docs/release-notes.md
> Update release notes for version 16.3.53 with new features and bug fixes

- docs/technical-details/reports/cloud-costs.md
> Updated Cloud costs docs

- docs/features/insights-cli.md
- docs/features/policies.md
> Support to Rego v0 and V1

- docs/features/insights-cli.md
- docs/features/policies.md
- docs/features/test.rego
> Added rego V1 examples

- docs/features/admission-controller.md
> INS-1087: Update insights docs with GKE instructions

- docs/features/infrastructure-as-code-scanning.md
> remove tfsec references

- docs/features/insights-cli.md
- docs/features/policies.md
> INS-1220: Update documentation to remove OPA v1

- docs/features/integrations.md
This PR enhance UTM Stack integration documentation
> Enhance UTM Stack integration documentation

- docs/features/integrations.md
> docs: enhance Datadog integration setup instructions
